### ISSUE TITLE
Tracking packages for accessing TCGA data

### ISSUE THREAD

**Issue by seandavi** [waldronlab/MultiAssayExperiment#120]
There are a lot of these, so I thought it might be useful to track them next to this project.  Here is a new one that I hadn't seen before.

http://www.liuzlab.org/TCGA2STAT/

Not at all Bioc compliant, but I like that the vignette has some minimal attempts at data integration and stats AFTER the data are downloaded into R.

**Comment by ttriche** [comment]
mother of christ some of their explanations of what the assays measure are
misleading


--t

**Comment by seandavi** [comment]
- https://www.bioconductor.org/packages/release/bioc/html/RTCGAToolbox.html
- http://www.compgenome.org/TCGA-Assembler/
- https://www.bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html

And a related package:

- http://www.cbioportal.org/cgds_r.jsp

**Comment by seandavi** [comment]
And the ISB Cancer Genomics Cloud BigQuery interface:

- https://github.com/isb-cgc/examples-R

**Comment by lwaldron** [comment]
For RTCGAToolbox, I recommend @LiNk-NY 's fork, which adds an extract method that creates standard Bioconductor objects: https://github.com/link-ny/rtcgatoolbox

**Comment by seandavi** [comment]
I asked a question on BioStars to get more input as well:

https://www.biostars.org/p/181996/

**Comment by lwaldron** [comment]
Posted on bioc-devel and released in 3.3: http://r-addict.com/2016/05/04/RTCGA-Quick-Guide.html

**Comment by seandavi** [comment]
Just informational, but looks like https://github.com/link-ny/rtcgatoolbox moved to https://github.com/waldronlab/TCGAmisc.

**Comment by LiNk-NY** [comment]
All of the helper functions that were in my fork of the `RTCGAToolbox` were moved to `TCGAmisc` for the time being. We are working on adding more helper functions to `TCGAmisc` and even renaming the package as such functions will not only be specific to TCGA data. 
The data downloading capabilities of the `RTCGAToolbox` remain largely the same in either my fork and the original (although there are some minor differences).
