### ISSUE TITLE
severe missingness in ovarian pData?

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#132]
ov is the readRDS of what we have in the S3 bucket

> table(pData(ov)$radiation_therapy, exclude=NULL)

  no  yes <NA> 
 557    5   29 

> table(pData(ov)$chemo_therapy)
> < table of extent 0 >
> table(pData(ov)$tumor_stage)
> < table of extent 0 >

**Comment by lwaldron** [comment]
The clinical data are messy, and we're working on merging the different datasets available to produce something more complete. It looks like it's not done yet for OVC, but in the meantime you could use:

```
patient.stage_event.clinical_stage
 stage iiic:408                    
 stage iv  : 89                    
 stage iiib: 25                    
 stage iic : 20                    
 stage ic  : 11                    
 (Other)   : 23                    
 NA's      : 15                    
```

and assume that every OVC patient received platinum and taxol chemotherapy.

**Comment by lwaldron** [comment]
I mean, it's not done yet in the MAE for any cancers, but for about 20 cancers we have a merged version of the clinical data prepared already.  By the way, cBioPortal provides only a few clinical variables which are quite an incomplete selection, although that may have some advantage over providing hundreds of variables...

**Comment by LiNk-NY** [comment]
This issue was moved to waldronlab/curatedTCGAData#26
