### ISSUE TITLE
enhance replacementMethod for ExperimentList

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#142]
allow the growth of an ExperimentList class by dynamically adjusting for the sampleMap when grown

**Comment by maddahi93** [comment]
Possibly support
```
mae[ , , 1:2] <- list(1:10, 10:1)
```

**Comment by LiNk-NY** [comment]
I still plan on looking into this.

**Comment by LiNk-NY** [comment]
This currently works.
