### ISSUE TITLE
implement coercion function from PharmacoSet to MultiAssayExperiment

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#158]
`as(object, "MultiAssayExperiment")` ?

**Comment by lwaldron** [comment]
That works.

**Comment by lwaldron** [comment]
Marcel, can you point me to any code you wrote while working on this?

**Comment by LiNk-NY** [comment]
https://github.com/LiNk-NY/PharmacoGx/blob/master/R/PharmacoSetClass.R#L1320
