### ISSUE TITLE
lintr-bot configuration

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#163]
Hi Jim, @jimhester
I'm not sure how this is configured. It started appearing automatically after commits (e.g., https://github.com/LiNk-NY/MultiAssayExperiment/commit/7f46227f039f591a0fe1ca2b69bca700a1e7d917)
Is it coming from codecov? 

I would like to have a Bioconductor lintr configuration. 

Thanks, 
Marcel

**Comment by jimhester** [comment]
It is coming from the lint step in https://github.com/vjcitn/MultiAssayExperiment/blob/4ef3320e5e4d717cd9aceedff55e4d4b3e7dfbf5/wercker.yml#L7

https://github.com/jimhester/lintr#non-failing-lints has some sparse documentation.

Linting with complete bioconductor style probably needs a few new linters written, to start with you need to turn off the camelCase linter and turn on the snake case one for instance. https://github.com/jimhester/lintr#project-configuration has some documentation on configuring it, you should be able to add a `.lintr` file to the project directory to add your configuration.

**Comment by LiNk-NY** [comment]
Great, thanks for the quick response!
