### ISSUE TITLE
please add the given method to allow subsetByRow with a VcfStack component

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#171]
setMethod("getHits", c("VcfStack", "GRanges"), function (subject, query, ...)
{
    intersect(seqnames(seqinfo(subject)), as.character(seqnames(query)))
})

### i don't know how to do it with the roxygen etc

**Comment by LiNk-NY** [comment]
Hi Vince @vjcitn, 
It seems to me that the right place for this `getHits` method should be in `GenomicFiles` with `MultiAssayExperiment` in the `Imports`? I'm in the process of removing methods for classes that are not directly related to `MultiAssayExperiment`. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
It would not be appropriate for GenomicFiles to depend / import MultiAssayExperiment; also getHits is a generic defined in MultiAssayExperiment, and I wonder whether the functionality provided by it is really required?

**Comment by LiNk-NY** [comment]
My motivation for this generic was to provide an intermediate step (before subsetting) to find the target rows and to standardize the output based on different inputs (`character` or `GRanges`). It can be simplified with some work.

**Comment by vjcitn** [comment]
I agree that this getHits concept needs some more review.  I don't see
anything about it
in the API document.  It seems to be an internal tool for the subsetBy
methods, and VcfStack
is a strange beast for subsetting.  I need to determine the relevant
chromosome,
and perhaps generate a relevant ScanVcfParam.  It would be nice to have
this ironed out soon.

**Comment by lwaldron** [comment]
Want to discuss during tomorrow's meeting? Marcel, can you still make it while you're in Buffalo?

**Comment by LiNk-NY** [comment]
Hi @lwaldron,
I'm back from Buffalo. I can discuss it during the meeting tomorrow. Thanks!
Regards,
Marcel
