### ISSUE TITLE
misleading documentation of `assay()` method with ranges

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#180]
From`?`assay,MultiAssayExperiment,missing-method`:

```
## S4 method for signature 'MultiAssayExperiment,missing'
assay(x, i, ...)
```

and under Arguments:

`i	Either a character, or GRanges object for subsetting by rows
`

However, to use a GRanges object with `assay()` requires the following, which doesn't seem to be documented:

`assay(x, ranges)`

**Comment by LiNk-NY** [comment]
There's a mix up between subsetting arguments and assay arguments. I will clarify the `i` documentation. Thanks!
