### ISSUE TITLE
assay,RangedRaggedAssay-method slow

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#181]
There is room for improvement in this function. Can be simplified with some work. 
#### get the matrix of genes x samples - this currently takes forever
```
cnvmat = assay(cnv, ranges = gr)  
```

**Comment by LiNk-NY** [comment]
This issue will be addressed in the newer iteration of this class.

**Comment by lwaldron** [comment]
I believe this issue is resolved by migration to the `RaggedExperiment` Bioconductor package.
