### ISSUE TITLE
Error in `RangedRaggedAssay` show method with non-numeric metadata column

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#182]
The GRangesList object is valid and I can do other things with the RRA, just now `show` - e.g. for the GBM TCGA object:

```
gbm <- readRDS("gbmMAEO.rds")
> experiments(gbm["EGFR", , "Mutations"])
ExperimentList class object of length 1: 
 [1] Mutations: RangedRaggedAssay with 102 rows and 290 columns 
> experiments(gbm["EGFR", , "Mutations"])[[1]]
RangedRaggedAssay with 102 disjoint ranges, 290 samples, and 73 data elements

Entrez_Gene_Id
Error in .local(x, i, ...) : metadata column is not numeric
> 
```

**Comment by lwaldron** [comment]
actually, the error also shows up in the `assay` and `reduce` methods on this RRA.

**Comment by LiNk-NY** [comment]
I've adjusted the show method to not call `assay`. 
That error:
```
Error in .local(x, i, ...) : metadata column is not numeric
```
Is related to calling assay on a non-numeric `mcols` column. You'd have to specify `mcolname`.

**Comment by lwaldron** [comment]
Thanks Marcel. Rectangularizing this mutations RRA is a little special - using all ranges within the ranges specified for a row, or all elements with the same gene name, something like:

`sum(Variant_Classification != "Silent" & Mutation_Status == "Somatic")
`
or:

`any(Variant_Classification != "Silent")
`
For when we have a little more time...

**Comment by LiNk-NY** [comment]
Hi @lwaldron, 
I can relax some of the requirements in `assay,RangedRaggedAssay-method` to work for non-numeric values. 

This would mean removing: 

* `is.numeric` check on the specified `mcolname` values
* `as.numeric` coercion to the `mcols` values when converting to matrix

**Comment by lwaldron** [comment]
I think this makes sense. Most of the time I would want to convert to a numeric matrix using rules such as above, but there could be cases where the user wants a matrix coming from some character `mcols`.

**Comment by LiNk-NY** [comment]
This should work now as of 11a285d9bfd99721654a1acff4f282fd9d53ffdd.
