### ISSUE TITLE
error in `rearrange` method for GBM object

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#183]
e.g.:

```
> gbm <- readRDS("gbmMAEO.rds")
> gbm2 <- gbm["EGFR", , c("RNASeq2GeneNorm", "mRNAArray", "RPPAArray", "gistica")]
> gbm2
A MultiAssayExperiment object of 4 listed
 experiments with user-defined names and respective classes. 
 Containing an ExperimentList class object of length 4: 
 [1] RNASeq2GeneNorm: ExpressionSet with 1 rows and 166 columns 
 [2] mRNAArray: ExpressionSet with 1 rows and 528 columns 
 [3] RPPAArray: ExpressionSet with 1 rows and 244 columns 
 [4] gistica: SummarizedExperiment with 1 rows and 577 columns 
To access: 
 experiments() - to obtain the ExperimentList instance 
 pData() - for the primary/phenotype DataFrame 
 sampleMap() - for the sample availability DataFrame 
 metadata() - for the metadata object of ANY class 
See also: subsetByAssay(), subsetByRow(), subsetByColumn()
> rearrange(gbm2)
Error: subscript contains invalid names
> 
```

**Comment by LiNk-NY** [comment]
Can you send me the `gbm2` object as an RDS? I can debug it.

**Comment by lwaldron** [comment]
Github allows .zip but not .rda, so here is a .rda.zip:

[gbm2.rda.zip](https://github.com/waldronlab/MultiAssayExperiment/files/743844/gbm2.rda.zip)

**Comment by lwaldron** [comment]
Actually I may as well give you another object that also has the mutations and gistic, for slightly more of a challenge:

`gbm3 <- gbm["EGFR", , ]
`
[gbm3.rda.zip](https://github.com/waldronlab/MultiAssayExperiment/files/743871/gbm3.rda.zip)

**Comment by LiNk-NY** [comment]
I fixed part of this in 111ae41058713d6e856d18277636d58a0cec4180

**Comment by LiNk-NY** [comment]
It looks like the data in `gbm3[["Mutations]]` is not numeric and is missing. 
See: 
`lapply(gbm3[["Mutations"]], function(x) mcols(x)["Score"])`
I'd have to check to see what happened with the data at some point in the pipeline.

**Comment by lwaldron** [comment]
I should check first that it wasn't bad subsetting...

**Comment by LiNk-NY** [comment]
The subsetting works but the data in `mcols` are blank characters.

**Comment by lwaldron** [comment]
`rearrange()` has been deprecated by `longFormat()` and `wideFormat()`. These work fine on `gbm3` except for the `Mutations` slot, but this is an issue with the RRA object or with reducing it. Revisit this with documentation when curatedTCGAData is read.

**Comment by LiNk-NY** [comment]
This can be revisited and posted in the `curatedTCGAData` issues page if need be. https://github.com/waldronlab/curatedTCGAData
