### ISSUE TITLE
Getting a matrix of genes x samples for RangedRaggedAssay

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#186]
Here is an example of things I tried for the AURKA gene in breast cancer (aurka.rda.zip attached):

```
## From brcaMAEO.rds:
> ## aurka <- brca["AURKA", !is.na(brca$PAM50.mRNA), c("Mutations")]
> unzip("aurka.rda.zip")
> load("aurka.rda")
> FUN1 = function(x) ifelse(any(x != "Silent"), 1, 0)
> x1=reduce(aurka[["Mutations"]], combine=FUN1, mcolname="Variant_Classification")
Warning messages:
1: In mean.default(mcols(singleRange)[[mcolname]][i]) :
  argument is not numeric or logical: returning NA
2: In mean.default(mcols(singleRange)[[mcolname]][i]) :
  argument is not numeric or logical: returning NA
> head(t(x1), 2)
                             20:54961339-54961339:+ 20:54961390-54961390:+
TCGA-A1-A0SD-01A-11D-A10Y-09                     NA                     NA
TCGA-A1-A0SE-01A-11D-A099-09                     NA                     NA
> x2=reduce(aurka, combine=FUN1, mcolname="Variant_Classification")
Error in .Method(..., deparse.level = deparse.level) : 
  number of rows of matrices must match (see arg 2)
In addition: Warning messages:
1: In mean.default(mcols(singleRange)[[mcolname]][i]) :
  argument is not numeric or logical: returning NA
2: In mean.default(mcols(singleRange)[[mcolname]][i]) :
  argument is not numeric or logical: returning NA
```

[aurka.rda.zip](https://github.com/waldronlab/MultiAssayExperiment/files/746465/aurka.rda.zip)

**Comment by LiNk-NY** [comment]
Hi @lwaldron, 

The error starts to happen at the `assay,RangedRaggedAssay-method` because the values in `Variant_Classification` are character and there are checks and coercions to numeric values (leading to `NA`s). 

Also, there seems to be very few ranges that have AURKA ranges. I only found 2 samples in the entire dataset. 

```
aukk <- aurka[[1L]][, lengths(aurka[[1L]]) > 0 ]
aukk
```

**Comment by lwaldron** [comment]
That's OK if there are few AURKA ranges. What I'm trying to do is get a numeric matrix of genes x patients, where each column indicates whether there is a non-silent mutation in that gene for that patient.

**Comment by LiNk-NY** [comment]
Hi Levi @lwaldron, 
I have changed the `assay,RangedRaggedAssay-method` to work with character values from the `mcols`. 

The `combine` argument is mostly for consolidating replicate samples so in this case, `reduce` wouldn't work.

Try this: 

```
charMat <- assay(aukk, mcolname = "Variant_Classification")
ifelse(charMat != "Silent", 1, 0)
```

**Comment by lwaldron** [comment]
What about the more general case where there can be 2+ variant classifications for the same gene or range? This is where I would use a function like:

`FUN1 = function(x) ifelse(any(x != "Silent"), 1, 0)`

to merge them.

**Comment by LiNk-NY** [comment]
Do you have an example? 
It seems to me like it is something that can be done as a pre-processing step on the `mcols` data column. Then, assay could be run with that column as the `mcolname` (once it's all 0s and 1s).
What do you think?

**Comment by lwaldron** [comment]
Here is an example:

```
> download.file("http://s3.amazonaws.com/multiassayexperiments/accMAEO.rds",
              destfile = "accMAEO.rds")
> acc <- readRDS("accMAEO.rds")
> allgenes <- unique(names(unlist(acc[["Mutations"]])))
> length(allgenes)
[1] 18320
> dim(acc[["Mutations"]])
[1] 20166    90
> 
```

I want `assay()` to return a 18320 by 90 numeric matrix, where each entry is 1 if there is at least one non-silent value of `Variant_Classification` and 0 otherwise. I would like to put a function in the metadata of the Mutations element of ExperimentList so that this would become the default behavior for `assay()` and by consequence `rearrange()` and I would no longer have to give special instructions each time I invoke `assay()` or `rearrange()`.

**Comment by lwaldron** [comment]
And I would look for the same behavior when using ranges, e.g.:

```
> allranges <- disjoin(unlist(acc[["Mutations"]]))
> length(allranges)
[1] 16190
> assay(acc, allgenes)  #returns 18320 x 90 matrix of 1 for non-silent mutation, 0 otherwise
> assay(acc, allranges) #returns 16190 x 90 matrix  of 1 for non-silent mutation, 0 otherwise
```

**Comment by LiNk-NY** [comment]
This seems to have been addressed in `RaggedExperiment`. I'm closing it.
