### ISSUE TITLE
reduce MAE should reorder

### ISSUE THREAD

**Issue by aedin** [waldronlab/MultiAssayExperiment#188]
Hi
When using reduce to subset the cases to the intersect, it should reorder the cases such that they are a common order
Aedin

**Comment by LiNk-NY** [comment]
Hi Aedin, @aedin 
Do you have an example I can work with? 
AFAIK, the operations in the `.harmonize` helper achieve this but there could be a bug. 

Regards,
Marcel

**Comment by lwaldron** [comment]
In my experience, `reduce()` does do this successfully - are you using a current development version Aedin?

**Comment by lwaldron** [comment]
I think that `reduce()` already does this. @aedin , please re-open if you have an example where it doesn't.

**Comment by lwaldron** [comment]
re-opened pending unit test.

**Comment by aedin** [comment]
Hi 
I was using the current version but I will check it. I will also you code I  used 
Aedin
