### ISSUE TITLE
subsetByColData()

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#192]
A growing preference for endomorphic verbs was mentioned to me at the microbiome workshop in Boston that Marcel, Lucas, and I are at.  (we currently have subsetByRow, subsetByColumn, and subsetByAssay). This one would have a usage something like:

`subsetByColData(myMultiAssayExperiment, sex=="M")`

that would be equivalent to:

`myMultiAssayExperiment[, myMultiAssayExperiment$sex=="M", ]`

Thoughts? Worthwhile?

**Comment by ttriche** [comment]
it's clearer what the first idiom is doing than the second, so yes,
probably worthwhile


--t

**Comment by lwaldron** [comment]
Close again after adding to cheatsheet.

**Comment by LiNk-NY** [comment]
Done.
