### ISSUE TITLE
as genomic components enter ExperimentList verify compatibility

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#193]
The seqinfo of each entity that bears such should be checked for consistency
with other ExperimentList elements.  We could add some code that coerces some
members to a common seqlevelsStyle if that is the only concern, throwing a warning,
or just error out.

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
This seems like a quality control type of helper. I have added a small function in [Bioconductor/MultiOmicQC](https://github.com/Bioconductor/MultiOmicQC) as an initial attempt. 
Regards,
Marcel

**Comment by vjcitn** [comment]
sounds good, thanks

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
Please create issues in the [Bioconductor/MultiOmicQC](https://github.com/Bioconductor/MultiOmicQC) repository. 
I have added a few functions since. 
Thanks,
Marcel
