### ISSUE TITLE
fail gracefully or subset for partly infeasible row selection

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#194]
> example(MultiAssayExperiment)
> myMultiAssayExperiment
A MultiAssayExperiment object of 4 listed
 experiments with user-defined names and respective classes. 
 Containing an ExperimentList class object of length 4: 
 [1] Affy: ExpressionSet with 2 rows and 4 columns 
 [2] Methyl450k: matrix with 2 rows and 5 columns 
 [3] RNASeqGene: matrix with 3 rows and 4 columns 
 [4] CNVgistic: RangedRaggedAssay with 5 rows and 3 columns 
Features: 
 experiments() - obtain the ExperimentList instance 
...

> myMultiAssayExperiment[1:3,]
Error: subscript contains out-of-bounds indices

Enter a frame number, or 0 to exit   

 1: myMultiAssayExperiment[1:3, ]
 2: myMultiAssayExperiment[1:3, ]
 3: .local(x, i, j, ..., drop = drop)
 4: subsetByRow(x, i, ...)
 5: subsetByRow(x, i, ...)
 6: rowIds[subsetor]
 7: rowIds[subsetor]
 8: subset_List_by_List(x, i)
 9: extractROWS(x[[k]], i[[k]])
10: extractROWS(x[[k]], i[[k]])
11: normalizeSingleBracketSubscript(i, x, allow.NAs = TRUE)
12: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, allow.NAs = a
13: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, allow.NAs = a
14: .subscript_error("subscript contains out-of-bounds indices")

but
myMultiAssayExperiment["XIST", ]  drops irrelevant experiments and succeeds

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
R, by default, won't let you subset an object if the subsetting index is out of bounds. We try to maintain this behavior for integer vector subsetting. This is mostly useful for a `head()` type of subset. 

For finer control, try using an `IRanges::IntegerList`: 
```
myMultiAssayExperiment[IRanges::IntegerList(1:2, 1:2, 1, 1), ]
```

**Comment by vjcitn** [comment]
OK, that makes sense.  Would you want to avoid the stack trace with
a pre-check and hint?  I can try to set up a patch...

**Comment by LiNk-NY** [comment]
That's a good idea. I will work on one.

**Comment by LiNk-NY** [comment]
I've added a check and a more descriptive error message. Is this what you had in mind? @vjcitn

**Comment by vjcitn** [comment]
yes, thanks!

**Comment by LiNk-NY** [comment]
Thank you for reporting!

**Comment by lwaldron** [comment]
Should it be max (abs (y)) in case user is using negative integer
subsetting? Weird case I know.

**Comment by LiNk-NY** [comment]
I think that negative integer subsetting is fair game for removing unwanted observations.

**Comment by lwaldron** [comment]
In that case I'd suggest adding the absolute value...

**Comment by LiNk-NY** [comment]
I mean that the out-of-bounds error only happens when the positive integers are used for subsetting. When negative integers are used, there is no error by default R behavior; 

```
vec <- 1:5
vec[-6]
```
When you do subset by a negative integer, it works as intended: 

```
rownames(myMultiAssayExperiment)
rownames(myMultiAssayExperiment[-3])
```

**Comment by lwaldron** [comment]
Thanks Marcel, I just learned something about base R integer subsetting!
