### ISSUE TITLE
experiment-specific `assay()` behavior

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#195]
The generally desired behavior of `assay()` is to return a list of numeric matrices, one per ExperimentList element. The `assay()` method for MultiAssayExperiment applies `assay()` to each ExperimentList element if the method exists, and defaults to the identity function I() if the method does not exist for that object class.

There are situations where an `assay()` method does not exist for a data class, but we would still like it to return a numeric matrix for the data object in a MultiAssayExperiment. For example, for segmented copy number as RangedRaggedAssay (soon to become RaggedExperiment, both based on GRangesList), we would like to find overlaps with a specified set of ranges (say corresponding to genes) that will form rows of the numeric matrix, assign a value from mcols(GRanges) where there is an overlap for each element of the GRangesList, and a background value (say 2 for a diploid organism) where there is no overlap.  For somatic mutations, which are represented in TCGA as vcf files, we might want to assign an integer value of the total number of non-silent mutations called in the range corresponding to each gene.

Rather than doing this through complicated `assay()` calls with a lot of arguments, I would propose using the metadata elements of the ExperimentList (derived from SimpleList) to store optional experiment-specific functions that do the job. For example:

```
> mae <- MultiAssayExperiment(experiments = list(muts = ragexp1, cn = ragexp2, rna = SE1), 
   +            assayfuns=list(muts=mutAssayFun, cn=cnAssayFun))
> metadata(experiments(mae))
$assayfuns
$assayfuns$muts
function(obj, ranges, background)
.......
$assayfuns$cn
function(obj, ranges)
> assay(mae, ranges=gr1, background=2)  #passing extra arguments through ...
$muts
(a numeric matrix)
$cn
(a numeric matrix)
$rna
(a numeric matrix)
```

Thoughts? @mtmorgan @LiNk-NY @vjcitn or others?

**Comment by kasperdanielhansen** [comment]
There are two issues here.

1) What to do about classes which do not have an assay() method
2) What to do with choice of defaults, if a method/function is often
invoked and needs a large amount of specialized arguments which are
nevertheless fixed for a specific MultiAssayExperiment

Re. 1): clearly the solution is to write an assay() method.  We have (or
should have) a list of requirements for any class to be used in
MultiAssayExperiment and this list includes subsetting on samples and (it
seems) the availability of an assay() method.

2) is much harder.  I agree that storing defaults (for multiple method /
functions) would be extremely convenient and thinking about this would be
useful.  This is especially an issue for MAE since the function calls are
already lengthy.

Best,
Kasper

**Comment by mtmorgan** [comment]
I think of generics as contracts, defining inputs and outputs that methods have to obey. SummarizedExperiment sets the generic and hence the contract. `assays()` (plural) returns a list of matrices; `assay()` returns a matrix, with the second argument determining element of the `assays()` to be returned.

For RaggedExperiment, assay() is defined and returns (probably the least useful but most consistent with class definition) 'sparseAssay()`.

I think the highly derived transformation you desire should just be a separate function, like 

```
> grep("Assay", ls(getNamespace("RaggedExperiment")), value=TRUE)
[1] "compactAssay" "disjoinAssay" "qreduceAssay" "sparseAssay" 
```

in RaggedExperiment. I don't think that there is value in storing these functions in the multi-assay experiment, because then they cannot be used in different contexts. Just write a function that validates that the input is the right type of object and does the right thing.

It might be desirable to create a subclass `setClass("MyRaggedExperiment", contains="RaggedExperiment")` and define a specific `assay()` method on that, or a plain-old function that checks to see that it's argument is a MyRaggedExperiment, but my feeling is that this is 'too clever by half'.

**Comment by vjcitn** [comment]
I am favorable to the idea of packing software with the data.  However, you
start to get into a situation where different objects of the same class may
behave very differently depending on what software is provided.  We should
ask for input fairly broadly.  Even if we go in this direction, I question
whether metadata() is the right place.  Perhaps a slot should be dedicated,
and some validity checking performed.  And indeed, it may be a reason to
introduce new classes with the desired behaviors.

**Comment by vjcitn** [comment]
Clearly I should have read down the responses before typing....

**Comment by lwaldron** [comment]
There's a lot to respond to, but this reply gets at some of @mtmorgan and @kasperdanielhansen 's comments. Martin, assay() already has a pretty loose contract with the MultiAssayExperiment; you are only assured that it will return a list. This is because we agreed earlier that requiring an assay() method that returns a numeric matrix was too stringent a requirement for membership in ExperimentList.  So when assay() is applied to a MultiAssayExperiment or ExperimentList, the elements of the returned list are the result of assay() on the ExperimentList element if defined for the class in that element, and the result of I() on the ExperimentList element if not. 

Martin - "I think the highly derived transformation you desire should just be a separate function" - those examples seem to be perfect for demonstrating the point. If I put a RaggedExperiment in my MAE object, how do I specify which should be used when I call assay(MAE)? I'm interested in decorating my MAE object to make assay(MAE) satisfy the stricter contract of returning a list of matrices, calculated the way I want, so that assay() and other nice functions like reshape() and reduce() will "just work". How would doing that make it so that these nice functions defined in RaggedExperiment "cannot be used in different contexts?" 

And when you say "Just write a function that validates that the input is the right type of object and does the right thing" - are you suggesting I write some equivalent of the assay() function for my particular MAE object that will do the right thing for each ExperimentList element? Doesn't that seem a lot more complicated than just writing that function for any element that needs a special function to do something more useful than the default assay()? As in your example, it was more logical to define new functions for different ways to coerce a RaggedExperiment to matrix than to define more classes. It seems more parsimonious / simpler as a user to decorate my MAE object with functions you've already provided in RaggedExperiment, rather than defining new classes and specific assay methods on those new classes.

I think this question will come up more as we start incorporating exotic classes derived from sparqlyr or who knows what database backend, where how to get a numeric matrix for statistical analysis is context-specific more than class-specific.

**Comment by LiNk-NY** [comment]
In response to the comments here, I have re-written the `assay` and `assays` methods to conform to the `SummarizedExperiment` contracts. See 95329fa29ecc4e45eaf45c9982e3fe36e117aec1. 
We are interested in a more complex implementation of the `assay` method but it seems this would have to be done in a separate function with a different name. 

It would be good to talk about the naming of some of these functions as some are also outside of their "contracts" and at the same time address some of the points in the manuscript reviews. 

@kasperdanielhansen Your point about classes not having an assay method is a good one. Right now, we can only add them to an ad-hoc `assay` method with a signature of `c("ANY", "missing")` but this will lead to an ever growing method definition. We could also impose an `assay` method for those classes as part of the API. 

Marcel

**Comment by lwaldron** [comment]
@mtmorgan - I fully agree with maintaining this assay contract, as MultiAssayExperiment now does:

> `assays()` (plural) returns a list of matrices; `assay()` returns a matrix, with the second argument determining element of the `assays()` to be returned.

But the contract doesn't specify *how* to generate those matrices in cases where it's not obvious, as can be the case with RaggedExperiments. It's normal for a generic function having class-specific methods, and I guess I'm suggesting that MultiAssayExperiment should also allow user-defined dataset-specific methods. One use case is when we have a segmented copy number dataset and a mutation dataset both represented as RaggedExperiment, but creating a genes x samples matrix from them should be handled differently. It seems more user-friendly to allow the user to insert their preferred method in the ExperimentList, and have the `assay(MultiAssayExperiment)` method recognize that, than to require the user to define a new class and new `assay()` method for it. It's important to have the `assay()` generic work as intended by the user on each element of the ExperimentList, for its own sake and because `assay()` is called by other things like `reshape()`. Another future use case I can think of is data classes representing a database backend, where some dataset-specific commands are necessary to extract data and convert it to a features x samples matrix.
