### ISSUE TITLE
translating ID <-> ID, and ID <-> ranges

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#196]
Along the lines of #195, `metadata(experiments(mae))` could contain another list element optionally providing functions through which any vector for row-based subsetting is passed. This would allow, for example:
- converting IDs to ranges for subsetting a range-based object (e.g. RangedSummarizedExperiment, RaggedExperiment)
- converting ranges to IDs for subsetting an ID-based object (e.g. matrix, ExpressionSet, SummarizedExperiment)
- converting IDs to IDs for subsetting by predicted targets of a microRNA, or translating one gene ID to another

@LiNk-NY @mtmorgan @vjcitn or others?

**Comment by mtmorgan** [comment]
As with https://github.com/waldronlab/MultiAssayExperiment/issues/195#issuecomment-288826032 it seems like this associates a function with an object, rather than creating a function that can be used across objects. I guess you're concerned that somehow it will be too hard to remember that function x is meant to be used to subset object y, but you have to remember that when creating object y, so...

**Comment by lwaldron** [comment]
I'm concerned that an MAE object has multiple objects which should be acted on simultaneously by a single assay() call, some of which require a special function to produce the desired behavior. So how does remembering that function x is meant to be used to coerce object y to a matrix help, if that memory isn't somehow formalized when I act on the MAE object as a whole?

**Comment by mtmorgan** [comment]
I think you're looking for something other than the simple contract provided by `assay()`, which is fine -- write another function with a  different name that does the highly specialized actions on very specifically formatted MAE.

**Comment by lwaldron** [comment]
Do you mean replace the current `assay()` method for MultiAssayExperiment with a generic of a new name?

**Comment by lwaldron** [comment]
I think this is asking for too much specificity in a very heterogeneous MAE. In cases where specialized subsetting is required, it will be better to create a derivative class and methods for those uses.
