### ISSUE TITLE
Fix pradMAEO-RTCGAToolbox vignette

### ISSUE THREAD

**Issue by lawremi** [waldronlab/MultiAssayExperiment#201]
That vignette still claims that RTCGAToolbox is from GitHub, but it's now on Bioconductor.  It looks like you are using readr for `type_convert()` but maybe you could instead just use `utils::type.convert()`. The function `buildMultiAssayExperiments()` seems broken because the variable `TCGAcodes` does not exist in the frame of the function (by my eye). Maybe `co` should be `cancerObject`? It should probably be put into some package, ideally RTCGAToolbox, which IMO should be giving us MAE's directly. Please also look into using BiocFileCache. 

From reading the vignette, I learned that there are many opportunities for improving how we access TCGA from Bioconductor, but that's another story.

**Comment by lwaldron** [comment]
Sorry about that - the risks of an unevaluated vignette. @schifferl I fixed a couple errors and got rid of the readr dependency, see [changes](https://github.com/waldronlab/MultiAssayExperiment/commit/91623e552a024b7f5ddcc75897a78d4331f664e3). @lawremi , the dependency on `BiocInstaller::biocLite("LiNk-NY/RTCGAToolbox")` is necessary, as this version added an extract function to generate basic Bioconductor objects (GRangesList, ExpressionSet, SummarizedExperiment), that the RTCGAToolbox maintainer hasn't incorporated. 

This vignette should soon be deprecated by [curatedTCGAData::curatedTCGAData()](https://github.com/waldronlab/curatedTCGAData/blob/master/R/curatedTCGAData.R).
