### ISSUE TITLE
no slot of name "colData" for this object of class "MultiAssayExperiment"

### ISSUE THREAD

**Issue by mdozmorov** [waldronlab/MultiAssayExperiment#205]
Attempt to use accMAEO.rds, gbmMAEO.rds results in 

Error in methods::slot(object, name) : 
  no slot of name "colData" for this object of class "MultiAssayExperiment"

Issue remains after upgrading R  and Bioconductor to the latest versions

**Comment by LiNk-NY** [comment]
Please use `updateObject` on the MultiAssayExperiment object. 
Regards, 
Marcel

**Comment by lwaldron** [comment]
You need to do:

```
library (RaggedExperiment)
mymae = updateObject (mymae)
```

It's noted on the spreadsheet, but apologies the error message isn't more
informative. The distribution method is being completely transitioned to
ExperimentHub and the MAEs there will soon be deprecated.

**Comment by mdozmorov** [comment]
Thanks, @LiNk-NY, @lwaldron, all works. Yes, overlooked big yellow highlight. Just wish the `updateObject` step would be behind the scenes. 
Thanks for the excellent package and the TCGA data in MultiAssayExperiment form!
Mikhail

**Comment by LiNk-NY** [comment]
Hi @mdozmorov,
BTW, this can't run behind the scenes because you're using a serialized instance of the `MultiAssayExperiment` object. We hope to get the data published in manageable pieces for easier download via `ExperimentHub`. 

Regards,
Marcel

**Comment by mdozmorov** [comment]
Looking forward, @LiNk-NY. The TCGA data within `MultiAssayExperiment` framework is very convenient to work with. Hope to see NCI60 and CCLE data in such format.
Mikhail
