### ISSUE TITLE
pradMAEO-RTCGAToolbox function definition

### ISSUE THREAD

**Issue by r-mvl** [waldronlab/MultiAssayExperiment#207]
In the function definition of pradMAEO-RTCGAToolbox, should "serialPath" not be "serialpath"?
Cheers

**Comment by LiNk-NY** [comment]
Thanks for catching that. Fixed. 
Regards,
Marcel

**Comment by r-mvl** [comment]
Hi Marcel,

Thanks for this. How updated are the files in the .rds objects? I found different total number of patients comparing the .rds file for PRAD compared to what’s available on cBioportal for example.

Many thanks,

Renaud

**Comment by LiNk-NY** [comment]
Hi Renaud, 
The serialized data is coming from the `RTCGAToolbox` where we have the last TCGA run date of Jan. 28, 2016. It may be possible that some patients were dropped if they had no data at all in the PRAD dataset. Throughout our pipeline, we strive to not remove any patients unnecessarily. 

We are also in the process of making cBioPortal data available as `MultiAssayExperiment` objects. 

We're happy to hear about any differences you've found between datasets. Thanks!

Regards,
Marcel
