### ISSUE TITLE
MultiAssayExperiment should contain Annotated

### ISSUE THREAD

**Issue by lawremi** [waldronlab/MultiAssayExperiment#208]
Rather than defining its own `@annotated` (of type "ANY" instead of "list"), MultiAssayExperiment should probably just contain the Annotated class.

**Comment by LiNk-NY** [comment]
@lawremi 
Are you referring to the `metadata` slot? I don't quite follow.

**Comment by lawremi** [comment]
yea

**Comment by lwaldron** [comment]
I'd like to revive this issue. The `setClass` statement of MultiAssayExperiment should have `contains = "Annotated"`, instead of `metadata = "ANY"`. Probably no one yet will even notice a difference, but inheriting from `Annotated` will allow tests like `is(mae, "Annotated")` to return TRUE.
