### ISSUE TITLE
package description

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/MultiAssayExperiment#211]
Could the description as displayed on the bioc landing page (http://bioconductor.org/packages/MultiAssayExperiment) which currently reads: “Develop an integrative environment where multiple assays are managed and preprocessed for genomic data analysis” be updated with a bit more informative description such as 2-3 key sentences as compiled from the abstract of the cancer research paper?

**Comment by lwaldron** [comment]
I fully agree, this sentence is a relic. How about:

> `MultiAssayExperiment` provides a data class and methods for coordinated representation, subsetting, reshaping, and other operations for experiments involving multiple different assays. It integrates any data class satisfying a few basic requirements, including eSet, (Ranged)SummarizedExperiment, matrix, and derived classes. The user interface is based on SummarizedExperiment, but assays may all have different numbers of rows and columns.

**Comment by LiNk-NY** [comment]
I was going to add something like: 
```
A coordinated representation of, storage of, and operation on
    multiple diverse 'omics experiments on a set of samples or specimen.
    MultiAssayExperiment provides data structures and methods for representing,
    manipulating, and integrating multi-assay experiments, as well as, a
    framework for integrative statistical analysis and visualization.
```

**Comment by LiNk-NY** [comment]
I could add the sentence mentioning the different classes that it supports.

**Comment by lgeistlinger** [comment]
I would keep it simple and also start with a biological motivation.
What about these sentences as directly extracted from your manuscript:

Multi-assay experiments, composed of multiple complementary data types for a set of samples, are increasingly commonplace in biomedical research and add layers of complexity to experimental design, data integration, and analysis.
The MultiAssayExperiment package implements data structures and methods for representing, manipulating, and integrating multi-assay experiments. This includes efficient construction, extraction, and subsetting of MultiAssayExperiment data structures. These methods are implemented matching Bioconductor user experience by straightforward extending concept and design of single-assay classes such as SummarizedExperiment or ExpressionSet for multi-assay experiments.

**Comment by lwaldron** [comment]
Some more copy and style editing:

> MultiAssayExperiment implements data structures
    and methods for representing, manipulating, and integrating multi-assay experiments
    via efficient construction, subsetting, and extraction operations.
    Methods emulate SummarizedExperiment as closely as possible to provide a familiar
    Bioconductor user experience, while providing simple and powerful approaches to 
    working with multi-omics data.
