### ISSUE TITLE
subsetByRow - assay selective subsetting

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#214]
The `subsetByRow` method should allow the user to subset a specific set of assays specified by the user. 

* Possible argument name: `experiments`
* Supported argument types: `character`, `logical`

**Comment by lwaldron** [comment]
I think this will be useful for studies where different assays use different kinds of identifiers. The argument name looks good to me, should supported types include `integer` also?

BTW when I get confused about whether to call something "assays" or "experiments" now I refer back to our Table 1 caption:

> Note. **assay** refers to a procedure for measuring the biochemical or immunological activity of a sample, e.g. RNA-seq, segmented copy number, and somatic mutation calls would be considered three different assays. **experiment** refers to the application of an assay to a set of samples. In general it is assumed that each experiment uses a different assay type, although an assay type may of course be repeated in different experiments. mae refers to a MultiAssayExperiment object. subject refers to patient, cell line, or other biological unit. observation refers to results of an assay, e.g. gene expression, somatic mutations, etc. features refer to measurements returned by the assays, labeled by row names or genomic ranges.

**Comment by LiNk-NY** [comment]
A newer implementation of this currently exists with the `subsetByRow,ExperimentList,list-method`. 
I don't think an argument should  be added here. The user can just convert the subsetting vector into a `list`. For example:
```
example(MultiAssayExperiment)
subsetByRow(myMultiAssayExperiment, list(Affy = 1:3))
```

**Comment by lwaldron** [comment]
Great implementation. Make sure to document it in the man page and the vignette!
