### ISSUE TITLE
Use of Endogenous in Vignette

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#215]
Section 4.8 is named "Subsetting is endogenous" but endogenous is not previously used to mean a function which returns the same type of variable as the input variable based on my searching. For example, Martin Morgran's [BioC Asia presentation](https://www.bioconductor.org/help/course-materials/2016/BiocAsia/Talk.pdf) uses "endomorphic" as does Hadley Wickham when describing dplyr. Is "endogenous" a misnomer?

**Comment by lwaldron** [comment]
Dario is right, this should read "endomorphic".
