### ISSUE TITLE
wideFormat additional arguments ignored?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#221]
I expected the following code to return a wide-format DataFrame of the "pvals" assay, but it instead returns the first assay in each SummarizedExperiment:

```
set.seed(1)
statvals <- matrix(rnorm(100), ncol=5)
rownames(statvals) <- paste0("pathway", 1:nrow(statvals))
colnames(statvals) <- paste0("cell", 1:ncol(statvals))
pvals <- pnorm(statvals)

coldat <- DataFrame(name=letters[1:5])
rownames(coldat) <- colnames(statvals)

library(SummarizedExperiment)
se1 <- SummarizedExperiment(list(statvals = statvals[1:12, ], pvals = pvals[1:12, ]))
se2 <- SummarizedExperiment(list(statvals = statvals[13:20, ], pvals = pvals[13:20, ]))
library(MultiAssayExperiment)
mae <- MultiAssayExperiment(list(database1=se1, database2=se2), 
                            colData=coldat)

res <- wideFormat(mae, colDataCols="name", i="pvals")
```

I expected res to contain pvals, but instead it contains statvals:

```
> all.equal(res[[3]], pvals[1, ], check.attributes=FALSE)
 [1] "Mean relative difference: 0.8231232" 
> all.equal(res[[3]], statvals[1, ], check.attributes=FALSE)
 [1] TRUE

```
 
I notice a couple places where ... are not passed to assay():

https://github.com/waldronlab/MultiAssayExperiment/blob/be090d411b9d6f3ca70f08d2d25d6b48be7c9fb4/R/MultiAssayExperiment-helpers.R#L272

https://github.com/waldronlab/MultiAssayExperiment/blob/be090d411b9d6f3ca70f08d2d25d6b48be7c9fb4/R/MultiAssayExperiment-helpers.R#L175

**Comment by LiNk-NY** [comment]
This special case was accounted for in e197ad5a4f2c03ca529c3b005c723676234cce2f

**Comment by LiNk-NY** [comment]
I've also removed the `wideFormat,ExperimentList-method` because the wide format returns a `DataFrame` with the same number of rows as in `colData` which is not available in a stand-alone `ExperimentList`.
