### ISSUE TITLE
ExperimentList Constructor Felxibility

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#225]
Would it be nicer if the `ExperimentList` list consructor was `ExperimentList(...)` and accepted name, value pairs? It would make the `MultiAssayExperiment` constructor slightly shorter and use less function calls because a list wouldn't need to be constructed as input if the multiple matrices weren't already in a list.

**Comment by LiNk-NY** [comment]
Hi Dario, @DarioS 

This is already implemented in the `devel` version of `MultiAssayExperiment`. 
Perhaps you're talking about the `release` version. Please include your session info. 
Thanks. 

Regards,
Marcel
