### ISSUE TITLE
combining MAE colData and SummarizedExperiment colData

### ISSUE THREAD

**Issue by jonaszierer** [waldronlab/MultiAssayExperiment#230]
If one of the experiments in an MAE has its own colData (e.g. a summarizedExperiment) it would be very convenient if wideFormat and longFormat could combine these with the MAE colData. 
For example in the TCGA data the tissue type (primary tumor/normal tissue/metastatic tumor) is sample-level information annotated in the summarisedExperiment colData. Combining it with the patient-level metadata (age/sex/tumor type/...) is rather cumbersome (as far as I know)

**Comment by LiNk-NY** [comment]
Hi Jonas, 

This seems like a feature that is outside of the MultiAssayExperiment API but it does
look like it would be useful as part of our [TCGAutils](https://github.com/waldronlab/TCGAutils) package. 

I can write up a quick function to allow you to combine `colData` from a `SummarizedExperiment`. 

Regards,
Marcel

**Comment by lwaldron** [comment]
Maybe there is a more general solution available through a `experimentColDataCols` argument. For `longFormat()` it seems like there is an unambiguous solution, but I am not sure what it should do in the `wideFormat()` example if, for example, there are tumor + normal for the same patient. Here's a [gist](https://gist.github.com/lwaldron/4137c0c4fe215590a35a874f3a0af04b) with a toy example where one assay has two observations for a single patient. What would you expect with

```
longFormat(myMultiAssayExperiment[1, 1:2, ], colDataCols="sex", experimentColDataCols="slope53")
```
and
```
wideFormat(myMultiAssayExperiment[1, 1:2, ], colDataCols="sex", experimentColDataCols="slope53")
```
for the output to be? I've put my response for `longFormat()` at the bottom.
```
> library(SummarizedExperiment)
> library(MultiAssayExperiment)
> example("MultiAssayExperiment", echo=FALSE)
> myMultiAssayExperiment[[1]] <- SummarizedExperiment(assays=exprs(myMultiAssayExperiment[[1]]), colData=pData(myMultiAssayExperiment[[1]]))
> myMultiAssayExperiment[[2]] <- SummarizedExperiment(myMultiAssayExperiment[[2]], colData=DataFrame(slope53=1:5))
> myMultiAssayExperiment[[3]] <- SummarizedExperiment(myMultiAssayExperiment[[3]])
> colData(myMultiAssayExperiment)
DataFrame with 4 rows and 2 columns
             sex       age
        <factor> <integer>
Jack           M        38
Jill           F        39
Bob            M        40
Barbara        F        41
> colData(myMultiAssayExperiment[[1]])
DataFrame with 4 rows and 1 column
           slope53
         <numeric>
array1 -0.13801711
array2  0.07012422
array3 -1.70098145
array4  0.48869170
> colData(myMultiAssayExperiment[[2]])
DataFrame with 5 rows and 1 column
          slope53
        <integer>
methyl1         1
methyl2         2
methyl3         3
methyl4         4
methyl5         5
> wideFormat(myMultiAssayExperiment[1, 1:2, ], colDataCols="sex")
harmonizing input:
  removing 6 sampleMap rows with 'colname' not in colnames of experiments
  removing 2 colData rownames not in sampleMap 'primary'
See ?mergeReplicates to combine replicated observations
  to get one column per variable
DataFrame with 2 rows and 9 columns
   primary      sex Affy_ENST00000294241_array1 Affy_ENST00000294241_array2
  <factor> <factor>                   <numeric>                   <numeric>
1     Jack        M                         101                          NA
2     Jill        F                          NA                         106
  Methyl450k_ENST00000355076_methyl1 Methyl450k_ENST00000355076_methyl2
                           <numeric>                          <numeric>
1                                  1                                  6
2                                 NA                                 NA
  Methyl450k_ENST00000355076_methyl3 RNASeqGene_XIST_samparray1 RNASeqGene_XIST_samparray2
                           <numeric>                  <numeric>                  <numeric>
1                                 NA                      84318                         NA
2                                 11                         NA                      84318
> longFormat(myMultiAssayExperiment[1, 1:2, ], colDataCols="sex")
harmonizing input:
  removing 6 sampleMap rows with 'colname' not in colnames of experiments
  removing 2 colData rownames not in sampleMap 'primary'
DataFrame with 7 rows and 6 columns
       assay primary         rowname    colname     value      sex
       <Rle>   <Rle>     <character>      <Rle> <numeric> <factor>
1       Affy    Jack ENST00000294241     array1       101        M
2       Affy    Jill ENST00000294241     array2       106        F
3 Methyl450k    Jack ENST00000355076    methyl1         1        M
4 Methyl450k    Jack ENST00000355076    methyl2         6        M
5 Methyl450k    Jill ENST00000355076    methyl3        11        F
6 RNASeqGene    Jack            XIST samparray1     84318        M
7 RNASeqGene    Jill            XIST samparray2     84318        F
> 
```

For `longFormat(myMultiAssayExperiment[1, 1:2, ], colDataCols="sex", experimentColDataCols="slope53")`, I think I would expect another column titled `slope53` containing `c(-0.13801711, 0.07012422, 1, 2, 3, NA, NA)`. But for melting this into `wideFormat()`, I'm not quite sure.

**Comment by LiNk-NY** [comment]
Hi Jonas, @jonaszierer 

Levi @lwaldron and I had a small discussion about the issue. 

We think assays should all be of one type. For example, you could have one assay for tumors and one assay for normals. We do have helper functions for extracting that information from sample barcodes. See [TCGAsampleSelect](https://github.com/waldronlab/TCGAutils/blob/master/R/TCGAsampleSelect.R) in the [waldronlab/TCGAutils](https://github.com/waldronlab/TCGAutils) package. Perhaps you were looking for this? 

In the case that these are just technical replicates, we would recommend that you use the `replicated` function to see them and consolidate them via the `mergeReplicates` function. You could then reintroduce the consolidated `assay` into the `SummarizedExperiment` and merge the `colData` within that `SummarizedExperiment`. 

An implementation of an `experimentColDataCols` argument would work best with biological units that have only one sample per assay or in a `MatchedAssayExperiment`. 

Creating a `wideFormat` with replicates starts getting complicated and could potentially violate the wide format contract of one biological unit per row. It would be better to resolve any replicates before trying to adjust for this type of case. 

It's also worth pointing out that the `MultiAssayExperiment` API doesn't require experiments to have a `colData` slot. A solution other than adding the `experimentColDataCols` argument would have to be independent of the main package and possibly contained in `TCGAutils` or in a different package. 

Regards,
Marcel

**Comment by jonaszierer** [comment]
Hi @LiNk-NY  and @lwaldron ,

yes I suppose it makes sense to split different conditions (healthy tissue vs. cancer tissue) of the same samples in different experiment slots. I haven't thought of this.

Best,
Jonas

**Comment by LiNk-NY** [comment]
Hi Jonas, @jonaszierer 

Please see the [TCGAutils](https://github.com/WaldronLab/TCGAutils) function, `separateSamples`. 
It does this operation quite conveniently for TCGA data.

This feature is still experimental and is in review (see Bioconductor/Contributions#597). 
There are some reported issues in `S4Vectors` that still need to be ironed out before
it can be fully functional. 

Best regards,
Marcel

**Comment by jonaszierer** [comment]
great thanks!
