### ISSUE TITLE
Omics Columns Without colData Dropped

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#234]
For some datasets in GEO Browser, the samples are a combination of tissue samples and cell lines. Tissue samples have associated clinical data but cell lines don't. The `MultiAssayExperiment` constructor drops any omics rows without an associated `colData` column.

```
dataset <- matrix(1:9, ncol = 3)
colnames(dataset) <- c("Patient X","Patient Y","Cell Line Z")
clinical <- data.frame(Age = 20:21, Gender = c("Male", "Female"), row.names = c("Patient X", "Patient Y"))
MultiAssayExperiment(list(omics = dataset), colData = clinical)

Warning message:
Cell Line Z dropped due to missing phenotype data
```

This seemingly creates the need for every omics sample corresponding to a cell line to have a row consisting entirely of `NA` in the sample details data frame, although the "colData slot requirements" section of the vignette doesn't specify that.

**Comment by lwaldron** [comment]
Hi Dario, @DarioS,

Thanks for the documentation report - I've added documentation of this requirement in the "colData slot requirements" section, which was previously only documented in the "`sampleMap`: relating `colData` to multiple assays" section. [Changes](https://github.com/waldronlab/MultiAssayExperiment/commit/81e7d9b280fa9b58fee22f615aa7db68ea2bbef8):

> Key points:
>  - one row of `colData` *can* map to zero, one, or more columns in any `ExperimentList` element
>  - each row of `colData` *must* map to at least one column in at least one `ExperimentList` element. 
>  - each column of each `ExperimentList` element *must* map to *exactly* one row of `colData`. 
> These relationships are defined by the `sampleMap`.

It is indeed a key requirement that every experimental observation must map to exactly one row of `colData`: the idea being that rows of `colData` provide information about the biological units, on which the experimental measurements are made and represented as columns in `ExperimentList`. In this conceptualization, an `ExperimentList` column with no corresponding `colData` row would be "orphaned": you wouldn't know which biological unit it came from, and it would never be touched by column subsetting operations or `longFormat`/`wideFormat` extractions. An `ExperimentList` column mapping to more than `colData` row would be ambiguous, seemingly coming from two different biological units. So in your example, yes you would have to fill in "NAs" for gender and age of the cell line to create a valid `MultiAssayExperiment` incorporating both patients and the cell line.
