### ISSUE TITLE
wideFormat Option To Use Sample Names as Row Names

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#235]
It'd be convenient if the `wideFormat` had an option allowing the user to choose where the sample IDs go. It'd avoid having to drop the first column whenever doing calculations. For example, `oneTable <- wideFormat(dataset, colDataCols = "aNumericColumn"); apply(dataset[, -1, drop = FALSE], function(column) abs(column - mean(column)))`

**Comment by lwaldron** [comment]
On the other hand, even if you don't want to use tidyverse functions on the `wideFormat()` `DataFrame` output, at least it provides a contract of what you can expect the output of `wideFormat()` to be, and the key you might use for rownames comes in the first column. My feeling is that `[, -1, drop=FALSE]` is no more complicated than specifying another argument to `wideFormat()`, and that the current contract is more strict and thus safer, and relies more on base functionality. I've sometimes thought I should have in my environment some function for coming back from the tidy world (like a less buggy version of this). Which is to say that it's a fairly general conversion that doesn't seem to me to belong hard-coded into `wideFormat()`, but as an additional step.

```
tidy2rownames <- function(obj, rownamescol=1){
  df <- data.frame(obj, stringsAsFactors=FALSE)
   rownames(df) <- df[, rownamescol]
   df <- df[, -rownamescol, drop=FALSE]
   return( df )
}
```

**Comment by DarioS** [comment]
I suppose that it's good to have less complexity in the codebase to manage.
