### ISSUE TITLE
wideFormat Code Optimisation

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#236]
Can you make it go faster? On a MultiAssayExperiment object with a single small matrix, it takes over 10 seconds.

```
> measurements
A MultiAssayExperiment object of 1 listed
 experiment with a user-defined name and respective class. 
 Containing an ExperimentList class object of length 1: 
 [1] matrix: matrix with 1706 rows and 17 columns
> dim(colData(measurements)) # Only 1 clinical column
[1] 17  1
> system.time(dataTable <- wideFormat(measurements, colDataCols = "class", check.names = FALSE))
   user  system elapsed 
 11.260   0.008  11.271
```

**Comment by DarioS** [comment]
On a more representative example with 20 thousand rows (i.e. typical human RNA microarray, RNA-seq before filtering, feature selection) and 20 samples, it took about 10 minutes on a computer I used, so it's not linear scaling but not quite quadratic either.

Perhaps the person who developed `stats::reshape` didn't have high-dimensional (bioinformatics) data in mind when implementing it as code all those years ago.

**Comment by LiNk-NY** [comment]
We moved to `stats::reshape` in order to get rid of some excess dependencies. I wonder how it compares to the previous code that used `tidyr::gather` and `tidyr::spread`.

**Comment by lwaldron** [comment]
@DarioS how is it now? This particular example is 7x faster for me now.

**Comment by DarioS** [comment]
It's fast.
