### ISSUE TITLE
wideFormat documentation is unclear

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#241]
If there is more than one sample per patient, `wideFormat` puts the samples into columns and the table has a lot of NA. I think this contradicts the documentation, which states "... each row represents an observation." I understand observation to mean sample, such as for a particular person's measurements before and after a treatment.

```
RNAmatrix <- matrix(1:25, nrow = 5, ncol = 5)
colnames(RNAmatrix) <- paste("Sample", 1:5)
rownames(RNAmatrix) <- paste("Gene", 1:5)

SNPmatrix <- matrix(sample(c("None", "Missense"), 25, replace = TRUE),
                    nrow = 5, ncol = 5)
colnames(SNPmatrix) <- paste("Sample", 1:5)
rownames(SNPmatrix) <- paste("Gene", 1:5)

patientData <- DataFrame(outcome = rep(c("Recovery", "Progression"), 2))
rownames(patientData) <- c("Person 1", "Person 2", "Person 3", "Person 4")
sMap <- DataFrame(assay = rep(c("RNA", "SNP"), each = 5),
                  primary = rep(c("Person 1", "Person 2", "Person 3", "Person 4", "Person 4"), 2),
                  colname = c(colnames(RNAmatrix), colnames(SNPmatrix)))

set <- MultiAssayExperiment(list(RNA = RNAmatrix, SNP = SNPmatrix),
                            colData = patientData, sampleMap = sMap)
wideFormat(set, colDataCols = "outcome")
```

I find the Details section is also ambiguous about what should happen in this scenario but the current output isn't directly usable for further analyses.

**Comment by LiNk-NY** [comment]
Hi Dario, @DarioS 

By "observation" we mean patient/person in this case. 
I will make changes in the documentation to clarify this. The reason there are many `NA`'s is
that `Person 4` has replicate samples. To get a more compact view, you'd have to
`mergeReplicates` or drop the replicates from the data.
This behavior is intended and we don't want to add rows for replicate observations.

Regards,
Marcel

**Comment by DarioS** [comment]
Thanks for the clarification about `wideFormat` functionality. Is there a variety of `wideFormat` I could use if I had a dataset with multiple metastases at different sites for each patient (1 patient:multiple sites samples) which would produce a DataFrame that could directly be used by R's logistic regression?

**Comment by DarioS** [comment]
It does.

**Comment by LiNk-NY** [comment]
Thanks for the feedback and responses. I'd like to keep this open in order to address documentation issues. 

Regards,
Marcel
