### ISSUE TITLE
Imports or Depends on S4Vectors

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#242]
When creating a `MultiAssayExperiment`, the user will almost always need to create a `DataFrame` object. Is it more streamlined to have a foundational package like S4Vectors in the Depends field of DESCRIPTION?

**Comment by LiNk-NY** [comment]
Hi Dario, @DarioS 
Thanks for your feedback. 
I will consider importing and exporting `DataFrame` from `S4Vectors`. 
Regards,
Marcel
