### ISSUE TITLE
dim() function

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#245]
`dim(MAE)` currently returns `NULL`. Maybe this is the best behavior, but I wonder if something like this would be a useful return? It returns # rows x # columns x # assays, but sets # rows to NA unless every assay has the same number of rows:

```
MAEdim <- function(x){
  rows <- unique(vapply(rownames(x), length, 1L))
  if(!identical(length(rows), 1L))
    rows <- NA
  c(rows, nrow(colData(x)), length(experiments(x)))
}
```

```
> MAEdim(miniACC)
[1] NA 92  5
> MAEdim(miniACC[, , 1])
harmonizing input:
  removing 13 colData rownames not in sampleMap 'primary'
[1] 198  79   1
> 
```

**Comment by LiNk-NY** [comment]
Hi Levi,
I think this would be a bit confusing to users. The same condition above could also apply to columns. 
Although complicated structures like `GRangesList` don't have any `dim` output, it might be useful to
provide an `IntegerList` for the `dim`-like output. This may be a bit more useful but it would break the dim contract. We could use a different function name to return these results. 

```
IRanges::IntegerList(lapply(experiments(myMultiAssayExperiment), 
```

-MR

**Comment by lwaldron** [comment]
There should be no confusion over columns, since in the `x[i, j, k]` notation the `j` corresponds to rows of `colData`. I'd thought of this as an indication of what integer square bracket makes sense, and if the assays have different numbers of rows then integer `[i, , ]` shouldn't be done, which was my rationale for returning an NA for rows in that case. Agreed that any `dim()` function would have to return an integer of length 3 as per contract.  I'm not sure of the value of the proposed `dim()` function, but I'm even less sure of the value of a new function name that returns an `IntegerList`.

**Comment by LiNk-NY** [comment]
We could also add something in the `show` method to denote the number of rows in `colData`.

**Comment by lwaldron** [comment]
The only point I disagree on is:

> Returning an integer of length 3 implies an array structure. MultiAssayExperiment is more of a
list type of object.

I'd argue that an important innovation of MultiAssayExperiment (and RaggedExperiment for that matter) is exactly that they present to the user as an array, with their list-like internals abstracted. That's why I think there's an argument for `dim()` returning something array-like for MAE and RE, but not for ExperimentList or GRangesList which make no attempt to be array-like. On the other hand,

```
IntegerList of length 4
[["Affy"]] 5 4
[["Methyl450k"]] 5 5
[["RNASeqGene"]] 5 4
[["GISTIC"]] 5 3
```

isn't array-like at all and doesn't give any hint as to what integers might belong in `mae[i, j, k]`. 

I'd still say do nothing, but this is an interesting discussion. I'd be curious to poll users and learn what most would expect `dim()` to return, if anything.
