### ISSUE TITLE
Extending MAE

### ISSUE THREAD

**Issue by p-smirnov** [waldronlab/MultiAssayExperiment#250]
After the discussions we had at Bioc2018 it seems that trying to fit non-square data into the MAE is probably not the most elegant solution, so I've been looking into how to extending the MAE class for Pharmacogenomics data by adding a slot for the sensitivity data and keeping all the molecular data as in a normal MAE. The goal would be to rewrite the PSet object as a subclass of MAE, so that users would have access to the MAE API for dealing with the molecular data (much better than our list of expressionsets currently in our PSet).

I think the logical place to store our Cell Line info (PSet@cell) slot would then be the colData of the MAE, as all of the omics datasets would map to the cell line names in the cell info slot as it is done in our PSet. However, I noticed that if I try to have entries in colData that do not exist in the primary column of sampleMap, they get removed by the constructor. 

The problem is that we often have cell lines that were only screened pharmacologically, and therefore would not be part of an assay in the ExperimentList inside the MAE, but rather would only exist in the other "sensitivity" slot. 

My current workaround for this is to add a placeholder assay to the ExperimentList which has one column for each sample that is included in the sensitivity slot. However, its not particularly ideal since I have to overload some of the functions to ignore this placeholder assay when operating on rows. 

Is there a better solution for this? I'm not sure how critical it is for the operation of the MAE object to have all the colData rows matched to at least one assay entry.

**Comment by vjcitn** [comment]
This is a good description of the problem, I think.

A question is: Can we use the non-square "back end" for the sensitivity
data that we have
discussed as an element of an ExperimentList?

-----

Classes contained in the ExperimentList must support the following list of
methods:

   - [: single square bracket subsetting, with a single comma. It is
   assumed that values before the comma subset rows, and values after the
   comma subset columns.
   - dimnames() : corresponding to features (such as genes, proteins, etc.)
   and experimental samples
   - dim(): returns a vector of the number of rows and number of columns

-----

Have you tried this?  I think it would be in the spirit of the
MultiAssayExperiment project to accommodate
the pharmacogenomics problem pretty directly.  Can we define an adapter
class that implements the
required methods usefully, sitting on top of the sensitivity store?  I
suspect so.

**Comment by jonocarroll** [comment]
FYI, @p-smirnov, I went that route and it's working out okay so far. Refer: https://github.com/waldronlab/MultiAssayExperiment/issues/239
