### ISSUE TITLE
function to add colData to a particular experiment and extract

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment#252]
This could be a standalone function to move the `colData(mae)` into a single
experiment during extraction (`[[`). 

_(from discussions with Levi @lwaldron)_

Samples and Patients should be in agreement in the final extracted dataset.

**Comment by schifferl** [comment]
This can sometimes be desirable when you only want a single assay from a `MultiAssayExperiment` object. In the context of `curatedTCGAData` I was able to achieve this with the following (not so elegant) code

**Comment by lgeistlinger** [comment]
Agreed with @schifferl. Would actually say that this is a frequent use case, for instance for users querying `curatedTCGAData` for a single assay type.

**Comment by LiNk-NY** [comment]
I've named it `getWithColData`, you can see it here: 17727a4a1e507a8987b30a8e6bf5f0579dbe043f

**Comment by lgeistlinger** [comment]
Thanks, Marcel!
