### ISSUE TITLE
fvarLabels-like accessor for MAE

### ISSUE THREAD

**Issue by lgatto** [waldronlab/MultiAssayExperiment#264]
I hope I haven't missed this functionality, but wouldn't it be useful to have an accessor that returns a list of rowData colnames, similar to `colnames(mae)` and `rownames(mae)`. I personally find it useful to easily find out what these assay's rowData contain.

In `Biobase`, this function is called `fvarLabels`. Other possible names would be `rowVarLabels` or `rowDataNames` to stick with the new naming conventions. 

It this is deemed of interest, I am happy to contribute such a generic and the method for the MultiAssayExperiment class. Something along the lines of

```r
> rowDataNames
function(x) {
    CharacterList(lapply(experiments(x),
                         function(xx) 
                             tryCatch(colnames(rowData(xx)),
                                      error = function(e) NA_character_)))
}
> rowDataNames(mae)
CharacterList of length 4
[["Affy"]] character(0)
[["Methyl450k"]] <NA>
[["RNASeqGene"]] <NA>
[["GISTIC"]] character(0)
```
but that also handles the `eSet` cases.

**Comment by lwaldron** [comment]
I wonder if we should export a derivative class for `MultiAssayExperiment` that guarantees that all `ExperimentList` elements inherit from `SummarizedExperiment`. That would simplify adding functionality like subsetting on element `rowData` or `colData`, without writing messy exceptions for `eSet` and any other non-SummarizedExperiment element. It would then be the user's responsibility to replace any `eSet` elements using `as(eset, "SummarizedExperiment")`.

**Comment by lwaldron** [comment]
@LiNk-NY, thoughts? Another option is to write some functionality for `SummarizedExperiment` elements that either drops or ignores non-`SummarizedExperiment` elements, depending on a `drop` argument.

**Comment by lgatto** [comment]
I wouldn't mind having an SE-only class (at the moment, at least), but this shouldn't become too restrictive in the future. If there are only SE, eSet and matrix objects to deal with, [this](https://github.com/rformassspectrometry/Features/blob/master/R/Features-class.R#L264-L274) could be enough in a first instance, with improvements only if required by relevant use-cases.

```r
rowDataNames <- function(object) {
    stopifnot(inherits(object, "MultiAssayExperiment"))
    CharacterList(lapply(experiments(object),
                         function(x) {
                             if (inherits(x, "SummarizedExperiment"))
                                 colnames(rowData(x))
                             else if (inherits(x, "eSet"))
                                 colnames(Biobase::fData(x))
                             else NA_character_
                         }))
}
```

**Comment by LiNk-NY** [comment]
Hi Levi and Laurent, @lwaldron @lgatto 

I think it would be good to have a derivative class that ensures that all elements in the `ExperimentList` are `SummarizedExperiment`. It would clean up and simplify operations that will then work seamlessly across the `SummarizedExperiments`.
Coercion could have the option of dropping any non-`SummarizedExperiment` elements with a warning. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Any thoughts Martin? @mtmorgan

**Comment by mtmorgan** [comment]
I don't know what the problem being addressed is. The 'lesson' from SummarizedExperiment seemed to be that it was better to define the 'api' required (anything with a dim() / dimnames() / [,]) rather than class ('must be a matrix') provided more flexibility.
