### ISSUE TITLE
Potential for upsetSamples mislabeling

### ISSUE THREAD

**Issue by jonocarroll** [waldronlab/MultiAssayExperiment#269]
I've somehow managed to end up in a situation whereby the factor levels of `sampleNames(MAE)[["assay"]]` do not have the same ordering as `names(MAE)`. The consequence of this was that `upsetSamples(MAE)` shows the wrong labels for experiments. It seems this can be prevented by using the same names in both the `split` and the resulting `incid` matrix

https://github.com/waldronlab/MultiAssayExperiment/blob/5212a92d38d45a5a6599ac38d79c4e88173e09d4/R/upsetSamples.R#L42-L51

by changing to

```r
colnames(incid) <- nameFilter(names(maesn)) 
```

without causing any damage.

**Comment by LiNk-NY** [comment]
Hi Jonathan, @jonocarroll 
Thank you for the report. I will look into it. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Note. It seems like this should be a validity check in `MultiAssayExperiment` but it is not a major issue. All subsetting operations use names instead of indices.
