### ISSUE TITLE
mcols on ExperimentList not propagated to MAE

### ISSUE THREAD

**Issue by vobencha** [waldronlab/MultiAssayExperiment#270]
Hi,

It looks like mcols on an ExperimentList aren't propagated to the final MAE.

Using the ExpList object from the man page example:
```
> example(MultiAssayExperiment)
> mcols(ExpList)
NULL
```

Add some mcols:
```
> mcols(ExpList) <- DataFrame(primary=c(TRUE, TRUE, FALSE, FALSE))
> mcols(ExpList)
DataFrame with 4 rows and 1 column
 primary
 <logical>
Affy TRUE
Methyl450k TRUE
RNASeqGene FALSE
GISTIC FALSE
```

Data aren't propagated to the MAE:
```
> mae <- MultiAssayExperiment(ExpList)
> mcols(experiments(mae))
NULL
```

Was this intended?

Thanks.
Val

**Comment by LiNk-NY** [comment]
Hi Val, @vobencha 
I hope you are well!
Sorry for the delay. It's close to release time and we've been busy
with packages. 
I will get to the issue today. 
Best,
Marcel

**Comment by vobencha** [comment]
No problem @LiNk-NY . Thanks for taking a look.
Val

**Comment by vobencha** [comment]
Thanks for the fix @LiNk-NY .
