### ISSUE TITLE
Expand documentation of setters and getters

### ISSUE THREAD

**Issue by llrs** [waldronlab/MultiAssayExperiment#281]
I was having some problems with `colData` and `sampleMap` and tried reading the documentation. However, I couldn't find there enough information to solve my problem: 

`?sampleMap` leads to the document MultiAssayExperiment-methods.Rd created by `R/MultiAssayExperiment-class.R`, `R/MultiAssayExperiment-methods.R`. It says "value: See details", but there isn't a details section. On the  Setters section is mentioned that "a `DataFrame` object relating samples to biological units and assays". But it doesn't explain that the value must have row names that match the primary key of `colData`, or how long, which columns should be provided. 

A more detailed description of the required conditions and formats for these functions to work will be appreciated. Thanks.

PS: Note that this is not detailed on the MultiAssayExperiment-class page

**Comment by LiNk-NY** [comment]
There is information about the value type in the method signature, e.g., `MultiAssayExperiment,DataFrame`.
I have added more information in the documentation. 
I would also refer you to the `prepMultiAssay` function which would help you find any issues with your data labels.
Thanks.
-MR

**Comment by llrs** [comment]
Great! Thanks for the reference, I missed it and just now I see it on the vignette. A link on "See Also" section of the MultiAssayExperiment-class might help to discover it from the help pages.
