### ISSUE TITLE
MAF to MAE

### ISSUE THREAD

**Issue by emmaroth** [waldronlab/MultiAssayExperiment#285]
Hi, I am working with some MAF data that I would ideally like to fit into a MAE. I am aware of bioconductor's MAFtools, but the output is not matrix based and thus not able to fit in to something like a SummarizedExperiment. Do you know of any ways to get MAF data into the ExperimentList?

**Comment by lwaldron** [comment]
RaggedExperiment (https://bioconductor.org/packages/RaggedExperiment/) is designed for ragged data like MAF and for compatibility with MultiAssayExperiment, with convenient features for subsetting by range, gene, etc and coercion to matrix format when needed. 

The MAF class exported by MAFtools is just a list so doesn't provide any of the methods that would are required for MultiAssayExperiment, and it wouldn't be so easy to make it so.
