### ISSUE TITLE
Tiny detail: warning when subsetting all assays

### ISSUE THREAD

**Issue by cvanderaa** [waldronlab/MultiAssayExperiment#294]
Hello!

I have a small issue with the new subsetting behavior. I understand there is now a warning that is thrown when experiments are dropped, but this also happens when subsetting all experiments (so no experiments are dropped), see:

```r
example("MultiAssayExperiment")
mae2 <- mae[, , 1:4]
metadata(mae2)
```
```
$drops.experiments
character(0)
```

It is for sure no major concern, only this makes some of our tests crash and I thought this is not very intuitive.

**Comment by LiNk-NY** [comment]
Hi Chris, @cvanderaa 
Thanks for pointing this out. I'll have a look at it today. 
Best,
Marcel

**Comment by cvanderaa** [comment]
Hi Marcel, @LiNk-NY 
Thanks a lot for this prompt fix!!
