### ISSUE TITLE
`na.rm` argument in `subsetByColData`

### ISSUE THREAD

**Issue by gogonzo** [waldronlab/MultiAssayExperiment#304]
Referring to the discussion in https://github.com/waldronlab/MultiAssayExperiment/issues/303
Please allow user to specify `na.rm` in `subsetByColData` to return data without any errors when column contains `NAs`

```r
library(MultiAssayExperiment)
subsetByColData(miniACC, DF$race == "white") # error
subsetByColData(miniACC, DF$race == "white", na.rm = TRUE) # to return a MAE without rows having NA in the condition
```

Thank you,
Dawid K

**Comment by LiNk-NY** [comment]
Thanks. 
We will update accordingly, depending on the result of the DataFrame issue https://github.com/Bioconductor/S4Vectors/issues/92.

**Comment by gogonzo** [comment]
Can `na.rm` be `TRUE`by default then - to keep it consistent with the MAE from Bioc < 3.14?

**Comment by LiNk-NY** [comment]
If this gets resolved in `DataFrame`, this option will not be needed.
