### ISSUE TITLE
Questions about `.sampleMapFromData()`

### ISSUE THREAD

**Issue by cvanderaa** [waldronlab/MultiAssayExperiment#314]
Hi Marcel, @LiNk-NY 

## Context

Laurent and I are maintaining the `QFeatures` class that directly inherits from the `MultiAssayExperiement` class.

I have been profiling the `QFeatures` code for adding [new assays](https://github.com/rformassspectrometry/QFeatures/blob/901daa92da9aeb1937001f0dea278a5c99d17e29/R/QFeatures-class.R#L679-L698) to the `QFeatures`. Our software is currently a bit slow for large single-cell proteomics datasets, and these will soon become larger... I have noticed that a lot of time is spent in `.sampleMapFromData()`, and more specifically [this line](https://github.com/waldronlab/MultiAssayExperiment/blob/9f71dd967bfc38550a4c0e22186a8bfe7f668957/R/MultiAssayExperiment-methods.R#L11):
```r
samps <- colnames(experiments)
```
Replacing this line with
```r
samps <- lapply(experiments, colnames)
```
leads to about a 30x gain in time (see example below). 

## Questions

1. What do think of this change? I understand that the use of `colnames()` is more elegant, but it leads to a big overhead. Would you be willing to adopt it in `MultiAssayExperiment`?
2. I have copied the function to `QFeatures`, but would rather prefer to call it from `MultiAssayExperiment` directly. Would you be willing to export this function as well so that we do not need to call to `MultiAssayExperiment:::`? 

If you agree on this, I can send a PR to spare you time. 

## Example

```r
## Improvement only available from very early devel of QFeatures
BiocManager::install("cvanderaa/QFeatures", ref = "issue104")

library(scpdata)
(qf <- specht2019v3()) ## a large `QFeatures` object

cd <- colData(qf)
el <- experiments(qf)
library(microbenchmark)
microbenchmark(MAE = MultiAssayExperiment:::.sampleMapFromData(cd, el),
               QF = QFeatures:::.sampleMapFromData(cd, el),
               times = 5)

```
```
Unit: milliseconds
 expr       min        lq      mean    median        uq       max neval
  MAE 708.17430 708.55089 711.39762 711.00339 712.72844 716.53106     5
   QF  22.17453  22.40136  23.51688  23.34302  24.18989  25.47558     5
```

**Comment by LiNk-NY** [comment]
Hi @cvanderaa 
The examples above do not give the same outputs. 
I can add a colnames,ExperimentList-method to make it faster. 
Best,
Marcel
