### ISSUE TITLE
Error = All sample identifiers in the assays must be unique

### ISSUE THREAD

**Issue by jfertaj** [waldronlab/MultiAssayExperiment#318]
Hello,

I am trying to create a MultiassayExperiment using two experiments (RNAseq and Proteomics). Both experiments are in matrix format.
The sampleMap file has no duplicates for RNAseq assay neither the Proteomics assay, but when running `MultiAssayExperiment` I get the following error:

"All sample identifiers in the assays must be unique"

I can't attach the files because they are protected

Thanks

**Comment by LiNk-NY** [comment]
Hi @jfertaj 
Can you provide a minimally reproducible example with fake data? 
Please include the version of `MultiAssayExperiment` and Bioconductor in the report in the `sessionInfo()`. 
Best,
Marcel
