### ISSUE TITLE
improve error message when assigning data.frame to colData

### ISSUE THREAD

**Issue by drighelli** [waldronlab/MultiAssayExperiment#330]
``I tried to assign a `data.frame` to the `colData` of a `MultiAssayExperiment`, giving me an `unused argument` error.

It might be nice to catch and improve the error message because it seems related to the unexpected data.frame class, using `DataFrame` nicely worked.

I don't have a reproducible example, but I can provide an example of the output.

```
> class(cd)
[1] "data.frame"
> colData(mae) <- cd
Error in .local(x, ..., value) : unused argument (value)
> colData(mae) <- DataFrame(cd)
> 
```

I hope this could be useful.

Dario

**Comment by LiNk-NY** [comment]
Hi Dario! @drighelli 
Thank you for reporting this. It is actually a bug in the `colData<-` call. I fixed it in both release (`1.30.2`) and devel (`1.31.2`). 
Best regards,
Marcel
