### ISSUE TITLE
experimental formula idiom for pairwise modeling and visualization

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#60]
The API document describes briefly the allLM.pw and pwplot functions now in biocMultiAssay.

The basic idea is that we can use a~b to isolate assays named 'a' and 'b' in the elist component.

yriMulti vignette has been updated to illustrate search through pairs of methylation scores and expression values using this idiom.

**Comment by mtmorgan** [comment]
Use of dots in function names is not considered good style; the concern is that they are mistaken (by computers or humans) as S3 methods on generic allLM for objects of class pw.

**Comment by vjcitn** [comment]
ah, thanks.  will change to underscore.

**Comment by LiNk-NY** [comment]
This seems out of date.
