### ISSUE TITLE
Add visual description of ExperimentList, etc. to MultiAssayExperiment-API document

### ISSUE THREAD

**Issue by mtmorgan** [waldronlab/MultiAssayExperiment#73]

**Comment by LiNk-NY** [comment]
see `MultiAssayExperiment::API()`

**Comment by vjcitn** [comment]
Is there something new here?  I was thinking of something graphical, at the
complexity level of the attached picture of SE, which
lays out names/dimensions/potential heterogeneities among MAE components.
 one would take the SE structure as given and then indicate how MAE is
populated and how relationships are established among MAE elements

whiteboard time

**Comment by LiNk-NY** [comment]
I see what you intend in the example here: 
http://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html
Perhaps this can go in the dashboard as well?

**Comment by vjcitn** [comment]
yes, and we need to make a new image that schematizes the MAE ... it will
take some effort, i think

**Comment by LiNk-NY** [comment]
*Update*: I have a sketch made in PPT. I can add it to the API.

**Comment by LiNk-NY** [comment]
See:
```
citation("MultiAssayExperiment")
```
