### ISSUE TITLE
integrate MultiAssayView

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#92]
From Martin's code [here](https://github.com/mtmorgan/biocMultiAssay/tree/feature/MultiAssayView). Lower priority.

**Comment by LiNk-NY** [comment]
Started on this with fd94bc8

**Comment by LiNk-NY** [comment]
@mtmorgan 
https://github.com/vjcitn/biocMultiAssay/blob/master/R/MultiAssayView-class.R#L108
I'm not sure how to update row/col/assay names to reflect MultiAssayView subsets...

**Comment by lwaldron** [comment]
How about instead of using separate slots for lists for row, col, and assay, make this a prototype of the "tall and skinny" data type.  So representation would just be subject = "environment", index = "DataFrame", where index has three columns: rowindex, colindex, assayindex, each an RLE.  Subsetting would be easy then.

By the way, I think MultiAssayExperiment can go into bioc-devel without MultiAssayView in place.

**Comment by lwaldron** [comment]
Actually, more informative names would be: `identifiers = "DataFrame"`, with columns: **rownames, colnames, assaynames**.  @mtmorgan what do you think of the change in design? I think the memory usage still scales as row + column if using RLE.

**Comment by LiNk-NY** [comment]
Sounds good. I think there should be an equivalent to reshape2::melt that returns DataFrames with RLE.

**Comment by LiNk-NY** [comment]
I don't think this issue is relevant to the aims of the package anymore. If someone thinks otherwise, please reopen the issue and update.
