### ISSUE TITLE
Proposal for RangedRaggedAssay

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment#98]
@mtmorgan @vjcitn @kasperdanielhansen We would like to be able to think of the RangedRaggedAssay as a rectangular dataset, even though it is not.  This could be accomplished as follows:
1. require `all(isDisjoint(rra))` for the RangedRaggedAssay "rra"
2. require the metadata slot of RangedRaggedAssay to contain a list with three elements:  1) $rowRanges, a disjoint GRanges with its first metadata column providing character IDs, 2) a numeric value (or NA) to assume for all ranges not covered by the GRanges for a sample, and 3) a list of optional arguments to findOverlaps() (can be empty).
3. `rownames(rra)` is unchanged, the names of the GRanges contained within the RRA.
4. `assay(rra)` would return a matrix comparably to `assay(myRangedSummarizedExperiment)`, with rownames from `metadata(rra)$rowRanges$feature_id`, and colnames from `colnames(rra)`. Wherever the GRanges from the rowRanges slot overlap with the GRanges for a sample, take the score for that range from the RangedRaggedAssay. Otherwise use the numeric value defined above.

**Comment by lwaldron** [comment]
Just to summarize, the basic idea is to add a GRanges object to the RangedRaggedAssay (for example, giving ranges of all genes). It would not affect subsetting, but the `assay()` extractor would then return a matrix, consistent with other Elist elements. The matrix would have one row per element of the GRanges object, and rownames from the names of the GRanges object.

**Comment by lwaldron** [comment]
Default $rowRanges GRanges in the RangedRaggedAssay constructor can be:

`disjoin(unlist(grl))`

The default for the second element can be NA, and NULL for the third.

**Comment by schifferl** [comment]
.checkDisjoint prevents type conversion of GRangesLists obtained using RTCGAToolbox

**Comment by lwaldron** [comment]
Which cancer type?  Could you post a .rds or .rda of a GRangesList object that it happens for?  I thought that GISTIC2 output would be disjoint per sample.

**Comment by LiNk-NY** [comment]
I just tried this on the Mutations COAD dataset from the RTCGAToolbox and I have 3 ranges that are not disjoint. These are all unique samples.
```
library(MultiAssayExperiment)
library(RTCGAToolbox)

coad <- getFirehoseData("COAD", runDate = "20151101", Mutation = TRUE, destdir = "/tmp")
cList <- extract(coad, "mutation")
table(isDisjoint(cList))
```
Based on your response, I will remove this requirement for the time being.

**Comment by LiNk-NY** [comment]
According to @lwaldron, the requirements for an assay method are that all ranges in the `GRangesList` be disjoint and have a "score" values column. With such column, we would be able to create the assay method for a RangedRaggedAssay (wrapper to a GRangesList). 

I have created a gist for downloading TCGA datasets and extracting a GRangesList of mutation data for different cancer types [here](https://gist.github.com/LiNk-NY/657f04c6c68bb5612504243e9a3e4275). 

@lima1 will be looking into this 

Please feel free to chime in.

**Comment by lwaldron** [comment]
@lima1 can you help with converting this GRangesList to a matrix?

**Comment by LiNk-NY** [comment]
Please see https://github.com/Bioconductor/RaggedExperiment
